[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["yuramishin <robothot@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.5"
alembic = "^1.14.0"
sqlalchemy = "^2.0.36"
dynaconf = "^3.2.6"
ruff = "^0.8.0"
mypy = "^1.13.0"
asyncpg = "^0.30.0"
uvicorn = "^0.32.1"
passlib = "^1.7.4"
pyjwt = "^2.10.1"
python-multipart = "^0.0.19"
jinja2 = "^3.1.5"
bcrypt = "^4.2.1"
aiohttp = "^3.11.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
run_app = "app.main:run_app"