[app_settings]
app_port=''
app_version=''
app_name=''
app_host=''
app_mount=''
app_api_key='357465a3-07cb-49c9-8619-7d2127741d69'

[db_settings]
db_name=''
db_user=''
db_password=''
db_host=''
db_port=''